### ISSUE TITLE
Guide to installation under Windows + Matlab

### ISSUE THREAD

**Issue by Bentoy13** [albarji/proxTV#13]
It's not an issue, but more a guide to install the toolbox proxTV on Windows with Matlab (and compilation with VS2010) for those interested.
In the installation guide, before running the `install` script, perform these steps:
1. Be sure that blas and lapack are installed. I use clapack v3.2.1.
2. Modify the following files:
- **utils.h**: append before lines 43-44 (defs of min and max functions) this block of preprocessor directives:

``` c
    #ifdef min
    #undef min
    #endif
    #ifdef max
    #undef max
    #endif
```

Root cause: on Windows `min` and `max` are already defined as macros, so deactivate them.
- **general.h**:
  - line 12: insert before this line the directive `#define _USE_MATH_DEFINES`. Root cause: `M_PI` is not defined by default when including `<math.h>`
  - lines 18-28: there are several problems under Windows. First, the type `lapack_int` is not seen equivalent as `integer`, but they must be the same, all are `long`. `lapack_int` is compiled as `ptrdiff_t`, raising compilation errors in at the calls of `dpttrf` and `dpttrs`. Another problem is about lapack. With clapack, there are 2 header files, `f2c.h` and `clapack.h`. These files are not protected against c++ name mangling. To fix both problems, replace lines 18-28 with this block:

``` c
    #ifdef NOMATLAB
    #undef lapack_int
    #define lapack_int          integer
    #ifdef __cplusplus
    extern "C" {
    #endif
    #include <f2c.h>
    #include <clapack.h>
    #ifdef __cplusplus
    }
    #endif
    inline double mxGetInf() { return INFINITY; }
    #else
    #include "mex.h"
    #ifdef __cplusplus
    extern "C" {
    #endif
    #include "f2c.h"
    #include "clapack.h"
    #ifdef __cplusplus
    }
    #endif
    #include "matrix.h"
    #define lapack_int          integer
    #endif
```
1. Modifications on `install.m`. I don't have put the include and lib directories of clapack in the path, so I must add the following options:
   - `-I"path/to/clapack/inc"` on every line calling mex.
   - replace all occurrences of `-lblas -llapack -lm` by `-L"path/to/lapack/lib/Release" -lblas -lf2c -llapack`.
     If you put clapack in the path, you don't need the `-I` and `-L`, but in all cases you need to replace `-lm` (not relevant with VC++) by `-lf2c` (libf2c.lib must be linked whenever you link lapack or blas).
     I don't use mwlapack, so I cannot tell you what to do to compile with this library.

Once you have done all of these instructions, run `install`, and the toolbox is installed!

**Comment by albarji** [comment]
Thanks a lot for this useful guide! I will add it to the docs in the next release. :+1:

I might also be able to include some of the changes you did in the defines in a way that works for both Linux and Windows. Will look into that.

**Comment by albarji** [comment]
Hi there,

I have been following your guide and everything works great up to the point when the mex interface files need to be generated. At that point, for instance when building

```
mex -v -lblas -lf2c -llapack CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_condat.cpp "*.obj"
```

I get the error message 

```
TVL1opt.obj : error LNK2019: unresolved external symbol dpttrs_ referenced in function PN_TV1
```

even though CLAPACK libraries are located in my PATH, and indeed by looking at the debug messages I can see that the mex compiler is finding them. So for some reason even if CLAPACK is being linked those symbols cannot be reached.

Did you experience any issue similar to this one?

Regards,
Álvaro.

**Comment by Bentoy13** [comment]
Hi Alvaro,

I was fighting the the same problem as you; at that time, I figured that my compilation of clapack was wrong, that I made an error when compiling this lib, that's why I didn't mention it in my guide. I'm very sorry for that/

So, as far as I remember ... it appears that the standard solution of clapack does not include all the files, in particular dpttrf.c and dpttrs.c (and many others). After spending a couple of hours for looking for these functions and a nice solution with it, I ended by a brute force solution: I added all the files of the source directory (for me, it's somthing like "[...]\clapack-3.2\clapack-3.2.1-CMAKE\SRC", where all *.c files are) to the project lapack. For that, just Add Existing Elements to the project lapack and select all files. Then, clean the whole solution and generate the libs. To avoid some troubles, I started with arithchk, f2c, then blas, then lapack.
At the end, check with dumpbin if the symbols dpttrt and dpttrs are there. You should see some lines with "SECTD  notype       Static       | $pdata$dpttrs_" for example, showing that these functions are in the lib.

Hope that will help you!

Sincerely yours,
Benoit

**Comment by albarji** [comment]
Yes! That was the root of the issue! Thanks Benoit! :+1: 
I remember now that I experienced similar problems a year ago. It seems that most precompiled versions of LAPACK+BLAS only include a very thin layer of the LAPACK functionalities. I compiled CLAPACK myself from sources using cygwin and with that I managed to install the library. :)

Now, I'm running the matlab demos I included in the library and strangely enough some of them throw a segmentation fault exception. These were heavily tested under Linux, so some strange behavior must be surfacing from the mex interfaces... did you experience any similar issue when putting the library to use?

Regards,
Álvaro.

**Comment by Bentoy13** [comment]
Hi,
I didn't run all the demos, only the 1D proxTV function, which is of great interest for me. No segfault for me on this function as far as I remember.
Indeed, if you have run strong tests, it should work under Windows. I may try to find some time to run some tests on my PC in the next days; hope we'll find a solution!
Best Regards,
Benoît

**Comment by sfmig** [comment]
I recently installed the toolbox proxTV on Windows with Matlab (compiled with Microsoft Visual C++ 2017), but followed slightly different steps. I leave them here in case it is useful for others.

1. I downloaded the code as zip and extracted it in the desired location
2. I modified the install.m script as follows:      ​
    - In the 'Compile C modules' section, ​I added the paths to the LAPACK and BLAS libraries that come with Matlab. For me they are located at c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft. The result looks like this:
      ```
      % Compile C modules
      mex -v -c -cxx CXXOPTIMFLAGS=-O3 CXXFLAGS='$CXXFLAGS -fopenmp -fPIC' LDFLAGS='$LDFLAGS -fopenmp' ...
          -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack ...
          -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas ...
          ../src/TVgenopt.cpp ../src/TVL1opt.cpp ../src/TVL1Wopt.cpp ...
          ../src/TVL2opt.cpp ../src/TVLPopt.cpp ../src/TV2Dopt.cpp ...
          ../src/TV2DWopt.cpp ../src/TVNDopt.cpp ../src/LPopt.cpp ...
          ../src/utils.cpp ../src/condat_fast_tv.cpp ../src/johnsonRyanTV.cpp ...
          ../src/TVL1opt_tautstring.cpp ../src/TVL1opt_hybridtautstring.cpp ...
          ../src/TVL1opt_kolmogorov.cpp
      ```
    -  In the 'Compile mex -v interfaces' section, ​I replaced the flags "-lblas -llapack -lm" with the paths to the LAPACK and BLAS libraries that come with Matlab. For me this solved the link error that was mentioned [in this same discussion](https://github.com/albarji/proxTV/issues/13#issuecomment-118940900). I also modified every *.o for *.obj. With these changes the section looks like this: 
        ```
        % Compile mex -v interfaces
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_condat.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_condattautstring.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_johnson.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_PN.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_linearizedTautString.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_classicTautString.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_hybridTautString.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV1_kolmogorov.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" TVL1Weighted.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" TVL1Weighted_tautString.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2_morec.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2_PGc.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2_morec2.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTVgen.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2D_DR.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2D_PD.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2D_CondatChambollePock.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2D_Yang.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2D_Kolmogorov.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV2DL1W.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV3D_Yang.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTVND_PDR.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTVp_GPFW.cpp "*.obj"
        mex -v -cxx -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwlapack -L"c:\Program Files\MATLAB\R2020b\extern\lib\win64\microsoft" -lmwblas CXXOPTIMFLAGS=-O3 CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" solveTV.cpp "*.obj"
        ```
3. I modified the references to dpttrf_ and dpttrs_, to dpttrf and dpttrs respectively, for the following files in the src directory: TVL1opt.cpp, TVL1Wopt.cpp, TVL2opt.cpp, TVLPopt.cpp. This is based on stuff I read online about _ being a UNIX convention. From [this post](https://www.mathworks.com/matlabcentral/answers/308688-unable-to-compile-using-mex-fmpc_sim-c-libmwblas-lib-libmwlapack-lib-undefined-reference-to-_dgem) in Matlab answers: the  'extra underscore _ at the end of the BLAS library names indicate UNIX convention names, but you are compiling on a Windows machine and these trailing underscores are not present in the names in the Windows versions of these libraries'.

4. Run install.m. The first section of install.m ('Compile C modules') makes the source cpp files into obj files in the 'matlab' folder. The second section of install.m ('Compile mex -v interfaces') takes the interface cpp files and the obj files in the 'matlab' folder and generates mexw64 files for the interfaces.

5. Check everything works well by trying out the demos. Following these steps I was able to run all of them.

The only thing I'd like to double check is about a point raised in [this post](https://www.mathworks.com/matlabcentral/answers/34202-solved-compile-mex-with-blas-under-windows) where they suggest replacing int for mwSignedIndex. If someone could offer guidance on that point that would be great. Thanks!
