### ISSUE TITLE
cannot install proxTV in python

### ISSUE THREAD

**Issue by jiankang1991** [albarji/proxTV#16]
[Anaconda2] C:\Users\karl>pip install prox-tv
Collecting prox-tv
  Using cached prox_tv-3.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\prox_tv.egg-info
    writing requirements to pip-egg-info\prox_tv.egg-info\requires.txt
    writing pip-egg-info\prox_tv.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\prox_tv.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\prox_tv.egg-info\dependency_links.t
xt
    writing manifest file 'pip-egg-info\prox_tv.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

```
running build_ext
building '_cffi__xeeb1e175x657f5e69' extension
creating c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv\_
```

_pycache__\Release
    creating c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv_
_pycache__\Release\prox_tv
    creating c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv_
_pycache__\Release\prox_tv__pycache__
    creating c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv_
_pycache__\Release\src
    C:\Users\karl\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\
9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DNOMATLAB=1 -Id:\u
sers\karl\anaconda2\include -Id:\users\karl\anaconda2\PC /Tcprox_tv__pycache__\
_cffi__xeeb1e175x657f5e69.c /Foc:\users\karl\appdata\local\temp\pip-build-phcqvm
\prox-tv\prox_tv__pycache__\Release\prox_tv__pycache___cffi__xeeb1e175x657f5e
69.obj -fopenmp
    cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
    _cffi__xeeb1e175x657f5e69.c
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(327) : warning C4013: 'Conda
tChambollePock2_TV' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(435) : warning C4013: 'DR2L1
W_TV' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(541) : warning C4013: 'DR2_T
V' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(630) : warning C4013: 'FISTA
_TVp' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(719) : warning C4013: 'FW_TV
p' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(808) : warning C4013: 'GPFW_
TVp' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(897) : warning C4013: 'GP_TV
p' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(986) : warning C4013: 'OGP_T
Vp' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1120) : warning C4013: 'PD2_
TV' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1254) : warning C4013: 'PD_T
V' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1324) : warning C4013: 'PG_T
V2' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1413) : warning C4013: 'PN_T
V1' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1509) : warning C4013: 'PN_T
V1_Weighted' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1565) : warning C4013: 'TV1D
_denoise' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1648) : warning C4013: 'Yang
2_TV' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1704) : warning C4013: 'dp'
undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1788) : warning C4013: 'more
PG_TV2' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1858) : warning C4013: 'more
_TV2' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1915) : warning C4013: 'taut
String_TV1' undefined; assuming extern returning int
    prox_tv__pycache___cffi__xeeb1e175x657f5e69.c(1979) : warning C4013: 'taut
String_TV1_Weighted' undefined; assuming extern returning int
    C:\Users\karl\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\
9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DNOMATLAB=1 -Id:\u
sers\karl\anaconda2\include -Id:\users\karl\anaconda2\PC /Tpsrc/condat_fast_tv.c
pp /Foc:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv__pycach
e__\Release\src/condat_fast_tv.obj -fopenmp
    cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
    condat_fast_tv.cpp
    C:\Users\karl\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\
9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DNOMATLAB=1 -Id:\u
sers\karl\anaconda2\include -Id:\users\karl\anaconda2\PC /Tpsrc/johnsonRyanTV.cp
p /Foc:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv__pycache
__\Release\src/johnsonRyanTV.obj -fopenmp
    cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
    johnsonRyanTV.cpp
    c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\src\johnsonRyanTV.
h(2) : error C2871: 'std' : a namespace with this name does not exist
    src/johnsonRyanTV.cpp(4) : error C2871: 'std' : a namespace with this name d
oes not exist
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\setup.py",
 line 68, in <module>
        zip_safe=False,
      File "d:\users\karl\anaconda2\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "d:\users\karl\anaconda2\lib\distutils\dist.py", line 953, in run_com
mands
        self.run_command(cmd)
      File "d:\users\karl\anaconda2\lib\distutils\dist.py", line 972, in run_com
mand
        cmd_obj.run()
      File "d:\users\karl\anaconda2\lib\site-packages\setuptools-19.4-py2.7.egg\
setuptools\command\egg_info.py", line 186, in run
      File "d:\users\karl\anaconda2\lib\site-packages\setuptools-19.4-py2.7.egg\
setuptools\command\egg_info.py", line 209, in find_sources
      File "d:\users\karl\anaconda2\lib\site-packages\setuptools-19.4-py2.7.egg\
setuptools\command\egg_info.py", line 293, in run
      File "d:\users\karl\anaconda2\lib\site-packages\setuptools-19.4-py2.7.egg\
setuptools\command\egg_info.py", line 322, in add_defaults
      File "d:\users\karl\anaconda2\lib\site-packages\setuptools-19.4-py2.7.egg\
setuptools\command\sdist.py", line 120, in add_defaults
      File "d:\users\karl\anaconda2\lib\distutils\cmd.py", line 312, in get_fina
lized_command
        cmd_obj.ensure_finalized()
      File "d:\users\karl\anaconda2\lib\distutils\cmd.py", line 109, in ensure_f
inalized
        self.finalize_options()
      File "d:\users\karl\anaconda2\lib\site-packages\setuptools-19.4-py2.7.egg\
setuptools\command\build_py.py", line 33, in finalize_options
      File "d:\users\karl\anaconda2\lib\distutils\command\build_py.py", line 46,
 in finalize_options
        ('force', 'force'))
      File "d:\users\karl\anaconda2\lib\distutils\cmd.py", line 298, in set_unde
fined_options
        src_cmd_obj.ensure_finalized()
      File "d:\users\karl\anaconda2\lib\distutils\cmd.py", line 109, in ensure_f
inalized
        self.finalize_options()
      File "c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\setup.py",
 line 19, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\setup.py",
 line 11, in get_ext_modules
        from prox_tv._prox_tv import _ffi
      File "c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv\__
init__.py", line 1, in <module>
        from ._prox_tv import *
      File "c:\users\karl\appdata\local\temp\pip-build-phcqvm\prox-tv\prox_tv_p
rox_tv.py", line 171, in <module>
        libraries=['lapack'])
      File "d:\users\karl\anaconda2\lib\site-packages\cffi\api.py", line 405, in
 verify
        lib = self.verifier.load_library()
      File "d:\users\karl\anaconda2\lib\site-packages\cffi\verifier.py", line 10
0, in load_library
        self._compile_module()
      File "d:\users\karl\anaconda2\lib\site-packages\cffi\verifier.py", line 19
6, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "d:\users\karl\anaconda2\lib\site-packages\cffi\ffiplatform.py", line
 38, in compile
        outputfilename = _build(tmpdir, ext)
      File "d:\users\karl\anaconda2\lib\site-packages\cffi\ffiplatform.py", line
 65, in _build
        raise VerificationError('%s: %s' % (e.__class__.**name**, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'C:\Users\karl\
AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin
\amd64\cl.exe' failed with exit status 2

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in c:\users\karl\app
data\local\temp\pip-build-phcqvm\prox-tv

[Anaconda2] C:\Users\karl>

I am new with python. what does it mean?

**Comment by albarji** [comment]
This might be related to issue #12 , please check whether that works for you.
