### ISSUE TITLE
cannot install proxTV in matlab windows10

### ISSUE THREAD

**Issue by jiankang1991** [albarji/proxTV#17]
I am not very familiar with compiler. When I install proxTV, it comes out error like this:

What should I do to fix it? Thank you very much.

> > install
> > Installing proxTV...
> > Verbose mode is on.
> > Neither -compatibleArrayDims nor -largeArrayDims is selected.
> >      Using -compatibleArrayDims. In the future, MATLAB will require the use of
> >      -largeArrayDims and remove the -compatibleArrayDims option.
> >      For more information:
> >      http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.
> > ... Looking for compiler 'MinGW64 Compiler (C++)' ...
> > ... Looking for environment variable 'MW_MINGW64_LOC' ...Yes ('C:\TDM-GCC-64').
> > ... Looking for file 'C:\TDM-GCC-64\bin\g++.exe' ...Yes.
> > ... Looking for folder 'C:\TDM-GCC-64\' ...Yes.
> > Found installed compiler 'MinGW64 Compiler (C++)'.
> > Set PATH = C:\TDM-GCC-64\bin;C:\Program Files\MATLAB\R2015b\extern\include\win64;C:\Program Files\MATLAB\R2015b\extern\include;C:\Program Files\MATLAB\R2015b\simulink\include;C:\Program Files\MATLAB\R2015b\lib\win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\MATLAB\R2015b\runtime\win64;C:\Program Files\MATLAB\R2015b\bin;C:\Program Files\MATLAB\R2015b\polyspace\bin;C:\TDM-GCC-64\bin
> > Set INCLUDE = C:\TDM-GCC-64\include;
> > Set LIB = C:\TDM-GCC-64\lib;;
> > Set MW_TARGET_ARCH = win64;
> > Set LIBPATH = C:\Program Files\MATLAB\R2015b\extern\lib\win64;
> > ## Options file details
> > 
> > ```
> > Compiler location: C:\TDM-GCC-64\
> > Options file: C:\Users\karl\AppData\Roaming\MathWorks\MATLAB\R2015b\mex_C++_win64.xml
> > CMDLINE2 : C:\TDM-GCC-64\\bin\g++ -m64 -Wl,--no-undefined -fopenmp -shared -s -Wl,"C:\Program Files\MATLAB\R2015b/extern/lib/win64/mingw64/mexFunction.def" TVgenopt.obj TVL1opt.obj TVL1Wopt.obj TVL2opt.obj TVLPopt.obj TV2Dopt.obj TV2DWopt.obj TVNDopt.obj LPopt.obj utils.obj condat_fast_tv.obj johnsonRyanTV.obj   -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -llibmx -llibmex -llibmat -lm -llibmwlapack -llibmwblas -o TVgenopt.mexw64
> > CXX : C:\TDM-GCC-64\\bin\g++
> > COMPILER : C:\TDM-GCC-64\\bin\g++
> > DEFINES : -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE 
> > MATLABMEX : -DMATLAB_MEX_FILE 
> > CXXFLAGS : -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC
> > INCLUDE : -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include"
> > CXXOPTIMFLAGS : -O3
> > CXXDEBUGFLAGS : -g
> > LDXX : C:\TDM-GCC-64\\bin\g++
> > LINKER : C:\TDM-GCC-64\\bin\g++
> > LDFLAGS : -m64 -Wl,--no-undefined -fopenmp
> > LDTYPE : -shared
> > LINKEXPORT : -Wl,"C:\Program Files\MATLAB\R2015b/extern/lib/win64/mingw64/mexFunction.def"
> > LIBLOC : C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64
> > LINKLIBS : -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -llibmx -llibmex -llibmat -lm -llibmwlapack -llibmwblas
> > LDOPTIMFLAGS : -s
> > LDDEBUGFLAGS : -g
> > OBJEXT : .obj
> > LDEXT : .mexw64
> > SETENV : set COMPILER=g++ 
> >             set COMPFLAGS=-c -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -DMATLAB_MEX_FILE  
> >             set OPTIMFLAGS=-O3 
> >             set DEBUGFLAGS=-g 
> >             set LINKER=g++ 
> >             set LINKFLAGS=-m64 -Wl,--no-undefined -fopenmp -shared -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -llibmx -llibmex -llibmat -lm -llibmwlapack -llibmwblas -Wl,"C:\Program Files\MATLAB\R2015b/extern/lib/win64/mingw64/mexFunction.def" 
> >             set LINKDEBUGFLAGS=-g
> >             set NAME_OUTPUT= -o "%OUTDIR%%MEX_NAME%%MEX_EXT%"
> > MINGWROOT : C:\TDM-GCC-64\
> > MATLABROOT : C:\Program Files\MATLAB\R2015b
> > ARCH : win64
> > SRC : F:\work_code\matlabToolBox\proxTV-master\src\TVgenopt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\TVL1opt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\TVL1Wopt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\TVL2opt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\TVLPopt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\TV2Dopt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\TV2DWopt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\TVNDopt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\LPopt.cpp;F:\work_code\matlabToolBox\proxTV-master\src\utils.cpp;F:\work_code\matlabToolBox\proxTV-master\src\condat_fast_tv.cpp;F:\work_code\matlabToolBox\proxTV-master\src\johnsonRyanTV.cpp
> > OBJ : TVgenopt.obj;TVL1opt.obj;TVL1Wopt.obj;TVL2opt.obj;TVLPopt.obj;TV2Dopt.obj;TV2DWopt.obj;TVNDopt.obj;LPopt.obj;utils.obj;condat_fast_tv.obj;johnsonRyanTV.obj
> > OBJS : TVgenopt.obj TVL1opt.obj TVL1Wopt.obj TVL2opt.obj TVLPopt.obj TV2Dopt.obj TV2DWopt.obj TVNDopt.obj LPopt.obj utils.obj condat_fast_tv.obj johnsonRyanTV.obj 
> > SRCROOT : F:\work_code\matlabToolBox\proxTV-master\src\TVgenopt
> > DEF : C:\Users\karl\AppData\Local\Temp\mex_193365832569327_1396\TVgenopt.def
> > EXP : TVgenopt.exp
> > LIB : TVgenopt.lib
> > EXE : TVgenopt.mexw64
> > ILK : TVgenopt.ilk
> > MANIFEST : TVgenopt.mexw64.manifest
> > TEMPNAME : TVgenopt
> > EXEDIR : 
> > EXENAME : TVgenopt
> > OPTIM : -O3
> > LINKOPTIM : -s
> > CMDLINE1_0 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVgenopt.cpp -o TVgenopt.obj
> > CMDLINE1_1 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVL1opt.cpp -o TVL1opt.obj
> > CMDLINE1_2 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVL1Wopt.cpp -o TVL1Wopt.obj
> > CMDLINE1_3 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVL2opt.cpp -o TVL2opt.obj
> > CMDLINE1_4 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVLPopt.cpp -o TVLPopt.obj
> > CMDLINE1_5 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TV2Dopt.cpp -o TV2Dopt.obj
> > CMDLINE1_6 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TV2DWopt.cpp -o TV2DWopt.obj
> > CMDLINE1_7 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVNDopt.cpp -o TVNDopt.obj
> > CMDLINE1_8 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\LPopt.cpp -o LPopt.obj
> > CMDLINE1_9 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\utils.cpp -o utils.obj
> > CMDLINE1_10 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\condat_fast_tv.cpp -o condat_fast_tv.obj
> > CMDLINE1_11 : C:\TDM-GCC-64\\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\johnsonRyanTV.cpp -o johnsonRyanTV.obj
> > ```
> > ---
> > 
> > Building with 'MinGW64 Compiler (C++)'.
> > C:\TDM-GCC-64\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVgenopt.cpp -o TVgenopt.obj
> > F:\work_code\matlabToolBox\proxTV-master\src\TVgenopt.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
> >  /**
> >  ^

C:\TDM-GCC-64\bin\g++ -c -DMX_COMPAT_32   -m64 -DMATLAB_MEX_FILE  -I"C:\Program Files\MATLAB\R2015b/extern/include" -I"C:\Program Files\MATLAB\R2015b/simulink/include" -fexceptions -fno-omit-frame-pointer -fopenmp -fPIC -O3 F:\work_code\matlabToolBox\proxTV-master\src\TVL1opt.cpp -o TVL1opt.obj
Error using mex
F:\work_code\matlabToolBox\proxTV-master\src\TVL1opt.cpp:1:0:
warning: -fPIC ignored for target (all code is position
independent)
 /**
 ^
F:\work_code\matlabToolBox\proxTV-master\src\TVL1opt.cpp: In
function 'int PN_TV1(double_, double, double_, double_, int,
double, Workspace_)':
F:\work_code\matlabToolBox\proxTV-master\src\TVL1opt.cpp:115:30:
error: 'dpttrf_' was not declared in this scope
     dpttrf_(&nnp,aux,aux2,&rc);
                              ^
F:\work_code\matlabToolBox\proxTV-master\src\TVL1opt.cpp:117:48:
error: 'dpttrs_' was not declared in this scope
     dpttrs_(&nnp, &one, aux, aux2, w, &nnp, &rc);
                                                ^

Error in install (line 25)
        mex -v -c -cxx CXXOPTIMFLAGS=-O3 CXXFLAGS='$CXXFLAGS
        -fopenmp -fPIC' LDFLAGS='$LDFLAGS -fopenmp' ...

**Comment by albarji** [comment]
I'm sorry about this problem, but I'm afraid this package is only officially supported for Linux platforms. Nevertheless please take a look at issue #13 and see if that guide can help you. In particular it seems like you are missing the blas and/or lapack libraries, a necessary prerequisite of this package.

**Comment by albarji** [comment]
@JianKangtum is this the same issue as #16 ??
