### ISSUE TITLE
Typo in doc?

### ISSUE THREAD

**Issue by fabianp** [albarji/proxTV#22]
The documentation for DR2_TV states that it solves a problem of the form 

   `min_w gam(f_1(w)+f_2(w)) + 0.5*norm(w)^2 -u^w`

Is this a typo and it should read `min_w gam(f_1(w)+f_2(w)) + 0.5*norm(w - u)^2` ?

**Comment by fabianp** [comment]
In particular I don't understand what does u^w mean in the original formula

**Comment by albarji** [comment]
Hi @fabianp , my apologies for the late reply.

There is indeed a typo: the optimization problem should read

   `min_w gam(f_1(w)+f_2(w)) + 0.5*norm(w)^2 - u · w`

the last term being the inner product of vectors u and w. This is nothing but a shifted version of 2-dimensional TV: if you complete the square using the two last terms you would get

   `min_w gam(f_1(w)+f_2(w)) + 0.5*norm(w-u)^2 - 0.5*norm(u)`

and you can drop the last (constant) term, obtaining the original 2-dimensional TV problem.
