### ISSUE TITLE
pls help me in resolving this

### ISSUE THREAD

**Issue by vithinvenkat** [albarji/proxTV#41]
In [4]: import prox_tv as ptv
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-1f9c55d04d95> in <module>()
----> 1 import prox_tv as ptv

/home/qpi2/anaconda3/lib/python3.6/site-packages/prox_tv/__init__.py in <module>()
     62 
     63 import numpy as np
---> 64 from _prox_tv import ffi, lib
     65 
     66 # The maximum number of returned info parameters.

ImportError: /home/qpi2/anaconda3/lib/python3.6/site-packages/_prox_tv.abi3.so: undefined symbol: __cxa_throw_bad_array_new_length

**Comment by albarji** [comment]
I'm afraid I have no clue about what the problem might be. Could you give me some more details on which platform you are running the code? Windows, Max, Linux?

**Comment by vithinvenkat** [comment]
thanks for your reply.solved it.updated conda.
