### ISSUE TITLE
Documentation clarification; monitoring objective functional along iterations

### ISSUE THREAD

**Issue by 1a7r0ch3** [albarji/proxTV#53]
Hi, thanks for sharing the code source.

First, I would like a clarification on the documentation, where problems and corresponding formulation are described. I understand that in line 1 and 4, the vertical bars in the expression |x_i  - x_{i-1}|  denotes the absolute value. But what about subsequent expressions with subscripted capital X, like |X_{i,:,:} - X_{i-1,:,:}|? My guess is that it is then a l1-norm; can you confirm this?

Second, I would like to know if it is possible to monitor the value of the objective functional which is minimized, along iterations?

Regards

**Comment by albarji** [comment]
Hi there!

Expressions in the form |x_i - x_{i-1}|  indeed refer to absolute values (or l1-norms). This is true for all the problems presented where this notation is used. When other norms are used (l2, lp) you will see that explicitly mentioned. Note also that proxTV can solve general lp variations of any of these problems (with p >= 1), see Generalized N-dimensional Anisotropic Total Variation. However, proxTV is mainly optimized for l1 problems.

Regarding monitoring the value of the objective being minimized, I'm afraid that is not possible directly. I tried to make the code as efficient as possible, and that involved reducing book-keeping and gathered statistics to a minimum. Nevertheless, some of the methods accept a max_iters parameter. For my performance experiments I called the same method several times with different max_iters, to have a look at how close the obtained solution is to optimum (max_iters = some large number). I don't know if this is good enough for you, though.

**Comment by 1a7r0ch3** [comment]
Thanks for your answer.
I ended up implementing the computation of the objective functional 
within your source code, with appropriate switches to turn off this 
functionality to enjoy full performance.
I do not propose a pull request because it is rather ugly : I compute 
offline the pairs of coordinates corresponding to the edges of the 
graph, it would be better not to resort to this. Of course if you are 
interested I could provide some pointers.
Hugo

**Comment by albarji** [comment]
Thanks for proposing the change, but I'd rather keep the code clean of this. Though my code is not something I would call "clean", but I'd rather not introduce additional complexity into it.
