### ISSUE TITLE
Bug in python tv1w_2d

### ISSUE THREAD

**Issue by emengd** [albarji/proxTV#9]
Hi,

Python function tv1w_2d doesn't seem to be working, and outputs its input. Here's a pylab example I ran :

```
>>> a = -array([[1,2],[3,4]])/10
>>> tv1w_2d(a, array([[1,1]]), array([[1],[1]]))
array([[-0.1, -0.2],
       [-0.3, -0.4]])
>>> tv1_2d(a, 1)
array([[-0.25, -0.25],
       [-0.25, -0.25]])
```

I wasn't able to figure out the problem.

**Comment by albarji** [comment]
Hi emengd,

Thanks for reporting this, I will look into it. I would expect such function to be working correctly, as it is used in the python demos and produces good results. But maybe in the case of this small matrix it doens't work properly. Have you tried with larger inputs?

**Comment by emengd** [comment]
Yes, it does work with larger inputs (as small as 3x3). I had only tried 2x2 as I was doing some tests in the command line for a function I had just written.

**Comment by albarji** [comment]
The problem turned out to be not with the inputs dimension but with the inputs type: some issues when arising when passing integer matrices down to the C core routines.

Automatic castings to float have been added when necessary to solve this problem.
